/**
 * @format
 */

import { AppRegistry } from 'react-native';
import { registerRootComponent } from 'expo';
import App from './App';
import { name as appName } from './app.json';

// Expo dev client / Expo Go look for "main".
registerRootComponent(App);

// The native Android/iOS shells generated by the RN template look for the
// name from app.json ("app"). Register it as well so both entry points work.
if (appName !== 'main') {
  AppRegistry.registerComponent(appName, () => App);
}
